12.0 credit memo checks 3093579 mpv
caldoor/odoo pull request #148
Opened 2023-03-15 22:18 UTC by mpv-odoo

Description
Adds credit notes into checks for the linked payments. 

Link to task: [3093579](https://www.odoo.com/web#model=project.task&id=3093579)

### All Submissions:

* [ ] My commit respects the [Odoo commit guideline](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#git)
* [ ] My commit message respects the [commit template](https://github.com/odoo-ps/psbe-process/wiki/Commits-message-guidelines#template)
* [ ] I have used pre-commit
* [ ] The PR contains **only** my modification and **no other external** commit

### Sh/Runbot:

* [ ] The commits pass test and the branch is green
* [ ] Unit tests have been implemented / standard ones rewritten
* [ ] The Staging is ISO-Prod and will contain only this dev

### Upgrade:

* [ ] The data affected (*if any*) by the changes has been migrated 

### Maintenance:

* [ ] The versions of the modules affected by the changes have been bumped in their manifests

2023-03-16 20:29 UTC, kak-odoo requested changes

2023-03-16 20:29 UTC, kak-odoo commented on caldoor_account_vendor_discounts/report/print_check.xml
> +                <t t-esc="stub_line.get('discount', '')"/>
This should probably just us `t-if` instead

2023-03-16 20:29 UTC, kak-odoo commented on caldoor_account_vendor_discounts/report/print_check.xml
>              <xpath expr="//td[4]/t" position="replace">
I know you didn't write this, but  this sort of direct indexing is bad, it's hard to follow and almost impossible to maintain, we should change it

2023-03-16 20:29 UTC, kak-odoo commented on caldoor_checks/report/print_check.py
> +import json
add a new line between the comment and the beginning of imports

2023-03-16 20:29 UTC, kak-odoo commented on caldoor_checks/report/print_check.py
> +from odoo.tools.misc import formatLang, format_date
Use correct import order: https://www.odoo.com/documentation/15.0/contributing/development/coding_guidelines.html#imports

2023-03-16 20:29 UTC, kak-odoo commented on caldoor_checks/report/print_check.py
> +        ''' END CHANGES '''
is all of this actually different, or at there just a bunch of smaller changes in this block?

2023-03-17 17:48 UTC, mpv-odoo commented on caldoor_account_vendor_discounts/report/print_check.xml
>              <xpath expr="//td[4]/t" position="replace">
So I did write this a while ago, but only because it was the only way to grab that t tag. The only unique thing about the tag was its `t-esc` but I can't select it based on that since there's no quote escape character in xpath (all the ones I tried didn't work). The alternative would be to essentially override the entire t-foreach, but I wasn't sure if that was better or worse. 

Here's the source code if you want to take a look at it: https://github.com/odoo/enterprise/blob/12.0/l10n_us_check_printing/report/print_check.xml#L54

2023-03-17 17:48 UTC, mpv-odoo commented on caldoor_checks/report/print_check.py
> +        ''' END CHANGES '''
Yeah it's all different.

2023-03-21 21:32 UTC, kak-odoo requested changes

2023-03-21 21:32 UTC, kak-odoo commented on caldoor_account_vendor_discounts/report/print_check.xml
>              <xpath expr="//td[4]/t" position="replace">
You will need to handle it at the xml level, so `//t[@t-esc=&quot;stub_line['amount_residual']&quot;]` should work

2023-03-21 23:48 UTC, kak-odoo requested changes

2023-03-21 23:48 UTC, kak-odoo commented on caldoor_checks/report/print_check.py
> +                amount_paid = float(invoice_stub_line.get('amount_paid').replace('$', '').replace(' ', ''))
Would using re make this cleaner? Also why are we stripping spaces?

2023-03-21 23:48 UTC, kak-odoo commented on caldoor_checks/report/print_check.py
> +                credit_amount = '(' + formatLang(self.env, credit_note.get('amount'), currency_obj=self.currency_id) + ')'
use string formatting

2023-03-21 23:48 UTC, kak-odoo commented on caldoor_checks/report/print_check.py
> +        return stub_pages
add a new line at the end of files

2023-03-22 21:31 UTC, bmu-odoo approved these changes

2023-03-22 21:43 UTC, merged